on:
  push:
    paths:
      - "**.hs"
      - "**.nix"
      - "flake.lock"
      - "agora.cabal"
    branches:
      - master
      - staging
  pull_request:
    paths:
      - "**.hs"
      - "**.nix"
      - "flake.lock"
      - "agora.cabal"
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/prepare-nix.yml
    secrets:
      CACHIX_KEY: ${{ secrets.CACHIX_KEY }}
    steps:
      - run: ./.github/format.sh
        name: Run fourmolu

  run-linter:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/prepare-nix.yml
    secrets:
      CACHIX_KEY: ${{ secrets.CACHIX_KEY }}
    steps:
      - run: nix run nixpkgs#hlint -- $(git ls-tree -r HEAD --full-tree --name-only | grep -E '.*\.hs')
        name: Run hlint

  check-build:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/prepare-nix.yml
    secrets:
      CACHIX_KEY: ${{ secrets.CACHIX_KEY }}
    steps:
      - name: Add cabal folder to cache
        id: cabal
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal
      - name: Build the project
        run: nix build
